server {
    listen      217.154.173.133:80;
    server_name situation.schnueddels.de ;

    include /home/webuser/conf/web/situation.schnueddels.de/nginx.conf_letsencrypt;

    location / {
        return 301 https://$host$request_uri;
    }
}
